// ARCHIVO GENERADO AUTOMÁTICAMENTE por scripts/generar-catalogo.ts
// Para regenerar: npm run generar-catalogo
// No editar manualmente — los cambios se sobreescriben al regenerar.

import type { Tipo, Color, Estampado, Estilo } from "./azure-openai";
export type { Tipo, Color, Estampado, Estilo };

export interface Producto {
  id: number;
  nombre: string;
  tipo: Tipo;
  color: Color;
  estampado: Estampado;
  estilo: Estilo;
  precio: number;
  imagen: string;
  link: string;
}

export const catalogo: Producto[] = [
  {
    id: 1,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 50000,
    imagen: "/productos/Captura de pantalla 2026-06-20 a la(s) 4.44.12 p. m..png",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 2,
    nombre: "Pantalon azul",
    tipo: "pantalon" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 45000,
    imagen: "/productos/Captura de pantalla 2026-06-20 a la(s) 4.44.19 p. m..png",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 3,
    nombre: "Blazer azul",
    tipo: "blazer" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 96000,
    imagen: "/productos/clangs-suit-2688317_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 4,
    nombre: "Camisa blanco",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 31000,
    imagen: "/productos/designfreek-ai-generated-8786357_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 5,
    nombre: "Jogger gris",
    tipo: "jogger" as Tipo,
    color: "gris" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 35000,
    imagen: "/productos/engin_akyurt-sweatpants-5173125_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 6,
    nombre: "Jogger gris",
    tipo: "jogger" as Tipo,
    color: "gris" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 47000,
    imagen: "/productos/engin_akyurt-sweatpants-5185570_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 7,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 46000,
    imagen: "/productos/loft184-fashion-3555646_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 8,
    nombre: "Sweater blanco",
    tipo: "sweater" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 93000,
    imagen: "/productos/mediamodifier-7cERndkOyDw-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 9,
    nombre: "Camisa blanco",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 37000,
    imagen: "/productos/pexels-armagan-basaran-107016502-18848213.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 10,
    nombre: "Vestido amarillo",
    tipo: "vestido" as Tipo,
    color: "amarillo" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 56000,
    imagen: "/productos/pexels-artografix-11421438.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 11,
    nombre: "Camisa marron",
    tipo: "camisa" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 47000,
    imagen: "/productos/pexels-chuvasher-11790168.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 12,
    nombre: "Pantalon marron",
    tipo: "pantalon" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 48000,
    imagen: "/productos/pexels-feet-1840619_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 13,
    nombre: "Vestido verde oliva geometrico",
    tipo: "vestido" as Tipo,
    color: "verde oliva" as Color,
    estampado: "geometrico" as Estampado,
    estilo: "casual" as Estilo,
    precio: 53000,
    imagen: "/productos/pexels-framesbyambro-11687577.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 14,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "boho" as Estilo,
    precio: 51000,
    imagen: "/productos/pexels-leeloothefirst-4869697.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 15,
    nombre: "Vestido negro",
    tipo: "vestido" as Tipo,
    color: "negro" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 75000,
    imagen: "/productos/pexels-magapls-2149937712-31649562.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 16,
    nombre: "Abrigo marron",
    tipo: "abrigo" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 193000,
    imagen: "/productos/pexels-miriam-alonso-7585604.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 17,
    nombre: "Camisa blanco",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 66000,
    imagen: "/productos/pexels-nkhajotia-1486058.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 18,
    nombre: "Pantalon azul",
    tipo: "pantalon" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "streetwear" as Estilo,
    precio: 40000,
    imagen: "/productos/pexels-pietro-henricky-1289770821-35568704.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 19,
    nombre: "Blazer amarillo",
    tipo: "blazer" as Tipo,
    color: "amarillo" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 132000,
    imagen: "/productos/pexels-rulomx-11588266.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 20,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 71000,
    imagen: "/productos/pexels-vhusko-8824538.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 21,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 50000,
    imagen: "/productos/stocksnap-skinny-2593347_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 22,
    nombre: "Abrigo marron",
    tipo: "abrigo" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 218000,
    imagen: "/productos/tobias-tullius-Fg15LdqpWrs-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 23,
    nombre: "Zapatos marron",
    tipo: "zapatos" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 52000,
    imagen: "/productos/tylermike525-oxford-shoes-6078951_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
];
