// ARCHIVO GENERADO AUTOMÁTICAMENTE por scripts/generar-catalogo.ts
// Para regenerar: npm run generar-catalogo
// No editar manualmente — los cambios se sobreescriben al regenerar.

import type { Tipo, Color, Estampado, Estilo } from "./azure-openai";
export type { Tipo, Color, Estampado, Estilo };

export interface Producto {
  id: number;
  nombre: string;
  tipo: Tipo;
  color: Color;
  estampado: Estampado;
  estilo: Estilo;
  precio: number;
  imagen: string;
  link: string;
}

export const catalogo: Producto[] = [
  {
    id: 1,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 63000,
    imagen: "/productos/Captura de pantalla 2026-06-20 a la(s) 4.44.12 p. m..png",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 2,
    nombre: "Pantalon azul",
    tipo: "pantalon" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 47000,
    imagen: "/productos/Captura de pantalla 2026-06-20 a la(s) 4.44.19 p. m..png",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 3,
    nombre: "Blazer azul",
    tipo: "blazer" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 94000,
    imagen: "/productos/clangs-suit-2688317_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 4,
    nombre: "Camisa blanco",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 63000,
    imagen: "/productos/designfreek-ai-generated-8786357_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 5,
    nombre: "Jogger gris",
    tipo: "jogger" as Tipo,
    color: "gris" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 49000,
    imagen: "/productos/engin_akyurt-sweatpants-5173125_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 6,
    nombre: "Jogger gris",
    tipo: "jogger" as Tipo,
    color: "gris" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 60000,
    imagen: "/productos/engin_akyurt-sweatpants-5185570_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 7,
    nombre: "Vestido blanco floral",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "floral" as Estampado,
    estilo: "casual" as Estilo,
    precio: 57000,
    imagen: "/productos/icsilviu-woman-5679284_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 8,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 72000,
    imagen: "/productos/jason-leung-EtOMMg1nSR8-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 9,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 78000,
    imagen: "/productos/loft184-fashion-3555646_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 10,
    nombre: "Sweater blanco",
    tipo: "sweater" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 85000,
    imagen: "/productos/mediamodifier-7cERndkOyDw-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 11,
    nombre: "Vestido rojo floral",
    tipo: "vestido" as Tipo,
    color: "rojo" as Color,
    estampado: "floral" as Estampado,
    estilo: "casual" as Estilo,
    precio: 54000,
    imagen: "/productos/oleg-ivanov-sg_gRhbYXhc-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 12,
    nombre: "Camisa blanco geometrico",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "geometrico" as Estampado,
    estilo: "casual" as Estilo,
    precio: 49000,
    imagen: "/productos/pexels-armagan-basaran-107016502-18848213.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 13,
    nombre: "Vestido amarillo",
    tipo: "vestido" as Tipo,
    color: "amarillo" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 47000,
    imagen: "/productos/pexels-artografix-11421438.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 14,
    nombre: "Camisa marron",
    tipo: "camisa" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 67000,
    imagen: "/productos/pexels-chuvasher-11790168.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 15,
    nombre: "Zapatos blanco",
    tipo: "zapatos" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 109000,
    imagen: "/productos/pexels-feet-1840619_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 16,
    nombre: "Vestido verde oliva geometrico",
    tipo: "vestido" as Tipo,
    color: "verde oliva" as Color,
    estampado: "geometrico" as Estampado,
    estilo: "casual" as Estilo,
    precio: 65000,
    imagen: "/productos/pexels-framesbyambro-11687577.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 17,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "boho" as Estilo,
    precio: 52000,
    imagen: "/productos/pexels-leeloothefirst-4869697.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 18,
    nombre: "Vestido negro",
    tipo: "vestido" as Tipo,
    color: "negro" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 37000,
    imagen: "/productos/pexels-magapls-2149937712-31649562.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 19,
    nombre: "Abrigo marron",
    tipo: "abrigo" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 120000,
    imagen: "/productos/pexels-miriam-alonso-7585604.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 20,
    nombre: "Camisa blanco",
    tipo: "camisa" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 63000,
    imagen: "/productos/pexels-nkhajotia-1486058.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 21,
    nombre: "Pantalon azul",
    tipo: "pantalon" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "streetwear" as Estilo,
    precio: 75000,
    imagen: "/productos/pexels-pietro-henricky-1289770821-35568704.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 22,
    nombre: "Blazer naranja",
    tipo: "blazer" as Tipo,
    color: "naranja" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 149000,
    imagen: "/productos/pexels-rulomx-11588266.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 23,
    nombre: "Vestido blanco",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 56000,
    imagen: "/productos/pexels-vhusko-8824538.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 24,
    nombre: "Vestido blanco floral",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "floral" as Estampado,
    estilo: "boho" as Estilo,
    precio: 51000,
    imagen: "/productos/sanskrutihomes-cRpcTf0VfuE-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 25,
    nombre: "Camisa rojo",
    tipo: "camisa" as Tipo,
    color: "rojo" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 52000,
    imagen: "/productos/souandresantana-t-shirt-7973394.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 26,
    nombre: "Camisa rojo",
    tipo: "camisa" as Tipo,
    color: "rojo" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 37000,
    imagen: "/productos/souandresantana-t-shirt-7973395.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 27,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 80000,
    imagen: "/productos/stocksnap-skinny-2593347_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 28,
    nombre: "Vestido blanco floral",
    tipo: "vestido" as Tipo,
    color: "blanco" as Color,
    estampado: "floral" as Estampado,
    estilo: "boho" as Estilo,
    precio: 45000,
    imagen: "/productos/sunriseforever-woman-10288088_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 29,
    nombre: "Abrigo marron",
    tipo: "abrigo" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 216000,
    imagen: "/productos/tobias-tullius-Fg15LdqpWrs-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 30,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 78000,
    imagen: "/productos/tuananh-blue-9yoXrG6Er_g-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 31,
    nombre: "Jean azul",
    tipo: "jean" as Tipo,
    color: "azul" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 53000,
    imagen: "/productos/tuananh-blue-j_3IlDX-6uQ-unsplash.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 32,
    nombre: "Zapatos marron",
    tipo: "zapatos" as Tipo,
    color: "marron" as Color,
    estampado: "liso" as Estampado,
    estilo: "formal" as Estilo,
    precio: 102000,
    imagen: "/productos/tylermike525-oxford-shoes-6078951_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
  {
    id: 33,
    nombre: "Camisa rojo",
    tipo: "camisa" as Tipo,
    color: "rojo" as Color,
    estampado: "liso" as Estampado,
    estilo: "casual" as Estilo,
    precio: 43000,
    imagen: "/productos/versionfrancaise-t-shirt-1710578_1920.jpg",
    link: "https://mercadolibre.com.ar",
  },
];
